name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install SwiftLint
        run: |
          brew update
          brew install swiftlint
          swiftlint --version
      - name: Run SwiftLint
        run: make lint

  swiftformat:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install SwiftFormat
        run: |
          brew update
          brew install swiftformat
          swiftformat --version
      - name: Run SwiftFormat
        run: make check
