name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      # @clover
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install SwiftLint
        run: |
          brew update
          brew install swiftlint
          swiftlint --version
      - name: Run SwiftLint
        run: make lint

  swiftformat:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      # @clover
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install SwiftFormat
        run: |
          brew update
          brew install swiftformat
          swiftformat --version
      - name: Run SwiftFormat
        run: make check
